import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ContactData } from "./types/home/contact";
import Footer from "./components/layout/Footer";
import { getData } from "./lib/getData";
import Header from "./components/layout/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const contact = await getData<ContactData>("/data/home/contact.json");

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-50 text-zinc-900 dark:bg-black dark:text-zinc-100 font-sans">
        <Header brandName={contact.name} />

        <main className="flex-1">
          {children}
        </main>

        <Footer name={contact.name} />
      </body>
    </html>
  );
}